package events

const (
	Key0          = "INPUT_KEY_0"
	Key1          = "INPUT_KEY_1"
	Key2          = "INPUT_KEY_2"
	Key3          = "INPUT_KEY_3"
	Key4          = "INPUT_KEY_4"
	Key5          = "INPUT_KEY_5"
	Key6          = "INPUT_KEY_6"
	Key7          = "INPUT_KEY_7"
	Key8          = "INPUT_KEY_8"
	Key9          = "INPUT_KEY_9"
	Up            = "INPUT_UP"
	Jump          = "INPUT_JUMP"
	Fly           = "INPUT_FLY"
	Down          = "INPUT_DOWN"
	Left          = "INPUT_LEFT"
	Right         = "INPUT_RIGHT"
	Use           = "INPUT_USE"
	Inventory     = "INPUT_INVENTORY"
	Wheel         = "INPUT_WHEEL"
	Primary       = "INPUT_MOUSE_PRIMARY"
	PrimaryDown   = "INPUT_MOUSE_PRIMARY_DOWN"
	Secondary     = "INPUT_MOUSE_SECONDARY"
	SecondaryDown = "INPUT_MOUSE_SECONDARY_DOWN"
	Move          = "INPUT_MOUSE_MOVE"
	Reload        = "INPUT_RELOAD"
	Enter         = "INPUT_ENTER"
	Shift         = "INPUT_SHIFT"
	Alt           = "INPUT_ALT"
	Map           = "INPUT_MAP"
)
